name: Update Lock File

on:
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        persist-credentials: false
        fetch-depth: 0
    - name: Update Poetry Lock File
      env:
        PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        sudo apt-get update
        sudo apt-get install --no-install-recommends wget ca-certificates
        sudo wget https://raw.githubusercontent.com/HibiKier/zhenxun_bot/main/pyproject.toml
        sed -i '8,11d' pyproject.toml
        python3 -V
        pip3 -V
        echo "Start install Poetry"
        sudo pip3 install poetry
        echo "Show Poetry Version"
        poetry --version
        rm requirements.txt
        echo "Export Requirements File"
        poetry export -f requirements.txt --output requirements.txt --without-hashes
        rm pyproject.toml poetry.lock
        ls -la --color
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.ZXBOTGIT_TOKEN }}
